enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.1.cjs

logFilters:
  - code: YN0002 # Peer dependency warnings
    level: "discard"
  # - code: YN0060 # Lockfile conflict warnings
  #   level: "discard"
  # - code: YN0086 # Peer dependency problems
  #   level: "discard"
