enableTelemetry: false

# nodeLinker: node-modules
nodeLinker: pnp

# pnpMode: loose

# pnpEnableInlining: true
# pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-4.8.1.cjs
# packageExtensions:
#   storybook@*:
#     peerDependencies:
#       "@storybook/react-vite": "*"
#       "styled-components": "*"
#   "@storybook/react-vite@*":
#     peerDependencies:
#       "vite": "*"
#       "styled-components": "*"
#   "@storybook/core@*":
#     peerDependencies:
#       "@storybook/react-vite": "*"
#       "styled-components": "*"
#   "@storybook/preview@*":
#     peerDependencies:
#       "styled-components": "*"
