services:
  - type: web
    name: ecommerce_server
    runtime: node
    buildCommand: |
      yarn install
      yarn turbo run @demo-shop/apps-server#build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: API_BASE_URL
        sync: false
      - key: API_KEY
        sync: false
