services:
  - type: web
    name: ecommerce_server
    runtime: node
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn workspace @demo-shop/apps-server start:prod"
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: API_BASE_URL
        sync: false
      - key: API_KEY
        sync: false
